version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/edgexfoundry/go-mod-core-contracts/v4"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-messaging/v4"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-registry/v4"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-secrets/v4"
        # Included when device-sdk-go is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-bootstrap/v4"
        # Included when device-sdk-go is updated          
