[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = ''  # blank value defaults to Service.Host value
Port = 49991
Protocol = 'http'
StartupMsg = 'device modbus started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res/example'
  UpdateLastConnected = false

# Pre-define Devices
[[DeviceList]]
  Name = 'Modbus TCP test device'
  Profile = 'Test.Device.Modbus.Profile'
  Description = 'This device is a product for monitoring and controlling digital inputs and outputs over a LAN.'
  labels = [ 'Air conditioner','modbus TCP' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-tcp]
       Address = '0.0.0.0'
       Port = '1502'
       UnitID = '1'
  [[DeviceList.AutoEvents]]
    Frequency = '20s'
    OnChange = false
    Resource = 'HVACValues'

[[DeviceList]]
  Name = 'Modbus RTU test device'
  Profile = 'Test.Device.Modbus.Profile'
  Description = 'This device is a product for monitoring and controlling digital inputs and outputs over a LAN.'
  labels = [ 'Air conditioner','modbus RTU' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-rtu]
       Address = '/tmp/slave'
       BaudRate = '19200'
       DataBits = '8'
       StopBits = '1'
       Parity = 'N'
       UnitID = '1'
